import { AsyncLocalStorage } from 'async_hooks';
import { Logger } from '@nestjs/common';
import { Prisma } from '@prisma/client';

const logger = new Logger('TenantGuard');

/**
 * CLS-like store so `bypassTenantGuard(fn)` lets a legitimate cross-tenant
 * operation (provisioning, cron sweep, domain resolver) opt out of the guard
 * for the duration of `fn`. Uses Node's native async_hooks so it correctly
 * propagates through awaits, promises, and BullMQ worker callbacks.
 */
const bypassStorage = new AsyncLocalStorage<boolean>();

/**
 * Run `fn` with the tenant guard bypassed. Use sparingly and only for code
 * paths that genuinely cross tenant boundaries (tenant provisioning, cleanup
 * cron, domain resolver, authentication lookups by token).
 */
export function bypassTenantGuard<T>(fn: () => Promise<T>): Promise<T>;
export function bypassTenantGuard<T>(fn: () => T): T;
export function bypassTenantGuard<T>(fn: () => T | Promise<T>): T | Promise<T> {
  return bypassStorage.run(true, fn);
}

export function isTenantGuardBypassed(): boolean {
  return bypassStorage.getStore() === true;
}

/**
 * Storage for the tenantId override we accept when CLS is unavailable
 * (scheduled jobs, webhook handlers, queue workers). The Prisma RLS
 * extension reads from this BEFORE consulting nestjs-cls — letting a
 * caller temporarily impersonate a tenant without standing up a full
 * Nest CLS context is the cheapest way to make scheduled per-tenant
 * work behave like a normal request.
 */
const tenantOverride = new AsyncLocalStorage<string>();

/**
 * Run `fn` as if the request came from `tenantId`. Use this in scheduled
 * jobs / webhook handlers when iterating per-connection so the queries
 * inside hit the correct RLS policy.
 *
 *   for (const conn of connections) {
 *     await runWithTenant(conn.tenantId, () => syncOrdersForConnection(conn.id));
 *   }
 */
export function runWithTenant<T>(
  tenantId: string,
  fn: () => Promise<T>,
): Promise<T>;
export function runWithTenant<T>(tenantId: string, fn: () => T): T;
export function runWithTenant<T>(
  tenantId: string,
  fn: () => T | Promise<T>,
): T | Promise<T> {
  return tenantOverride.run(tenantId, fn);
}

export function getTenantOverride(): string | undefined {
  return tenantOverride.getStore();
}

/**
 * Assert that a write payload contains a tenantId. Call from service write paths
 * until the Prisma extension is wired in Phase 2.
 */
export function assertTenantWrite(model: string, data: unknown): void {
  if (isTenantGuardBypassed()) return;
  if (!TENANT_SCOPED_MODELS.has(model)) return;
  if (!dataHasTenantId(data)) {
    throw new TenantGuardError(
      `TenantGuard: write to ${model} without tenantId in data`,
    );
  }
}

/**
 * Assert that a where clause scopes by tenantId (directly or via AND/OR).
 */
export function assertTenantWhere(model: string, where: unknown): void {
  if (isTenantGuardBypassed()) return;
  if (!TENANT_SCOPED_MODELS.has(model)) return;
  if (!whereHasTenantId(where)) {
    throw new TenantGuardError(
      `TenantGuard: query on ${model} without tenantId filter`,
    );
  }
}

/**
 * Models with a `tenantId` column that must be scoped per tenant.
 * Derived from prisma/schema.prisma — add a new model here whenever you add one.
 *
 * Generated by:
 *   grep -B 10 "tenantId  *String" prisma/schema.prisma | grep "^model " | awk '{print $2}' | sort -u
 */
export const TENANT_SCOPED_MODELS: ReadonlySet<string> = new Set([
  'Account',
  'Address',
  'AttributeTranslation',
  'AuditLog',
  'BackgroundJob',
  'Bank',
  'BankAccount',
  'BankMatchingRule',
  'BankReconciliation',
  'BankReconciliationDetail',
  'BankTransaction',
  'Batch',
  'BinBalance',
  'Cart',
  'CartItem',
  'CategoryTranslation',
  'Contact',
  'ContactLink',
  'ContentTranslation',
  'Coupon',
  'CouponUsage',
  'Customer',
  'EmailBounce',
  'EmailVerificationToken',
  'FailedOperation',
  'GiftCard',
  'GiftCardTransaction',
  'GlEntry',
  'Item',
  'ItemAttributeType',
  'ItemAttributeValue',
  'ItemUom',
  'Location',
  'MarketplaceCampaign',
  'MarketplaceConnection',
  'MarketplaceListing',
  'MarketplaceMessageThread',
  'MarketplaceOrder',
  'MarketplaceReturn',
  'MarketplaceSyncLog',
  'MarketplaceViolation',
  'Notification',
  'OAuthState',
  'Order',
  'OrderItem',
  'PasswordReset',
  'Payment',
  'ProductCategory',
  'ProductImportJob',
  'ProductListing',
  'ProductPriceOverride',
  'ProductReview',
  'ProductTranslation',
  'ProductVariant',
  'RefreshToken',
  'Serial',
  'Shipment',
  'ShipmentEvent',
  'ShippingCarrier',
  'ShippingRate',
  'ShippingRateTranslation',
  'ShippingWeightTier',
  'ShippingZone',
  'StockFifoLayer',
  'StockLedgerEntry',
  'StockLedgerEntrySerial',
  'StockPosting',
  'StoreAddress',
  'StoreCurrency',
  'StoreCustomer',
  'StoreCustomerPreferences',
  'StoreLanguage',
  'StorePage',
  'StoreTheme',
  'Supplier',
  'User',
  'VariantPriceOverride',
  'Warehouse',
  'WarehouseItemBalance',
  'Webhook',
]);

/**
 * Operations that always carry the tenantId in `data` (or `create` for upsert).
 */
const WRITE_CREATE_OPS: ReadonlySet<string> = new Set(['create', 'createMany', 'upsert']);

/**
 * Operations that must filter by tenantId in `where`.
 */
const WRITE_UPDATE_OPS: ReadonlySet<string> = new Set([
  'update',
  'updateMany',
  'delete',
  'deleteMany',
]);

/**
 * Read operations where we want the tenantId filter to be present.
 */
const READ_OPS: ReadonlySet<string> = new Set([
  'findFirst',
  'findFirstOrThrow',
  'findMany',
  'count',
  'aggregate',
  'groupBy',
]);

/**
 * findUnique/findUniqueOrThrow take a unique where clause. If the unique key
 * includes tenantId we're fine; otherwise we can't easily enforce here and
 * must trust the model-level composite-unique design.
 */
const READ_UNIQUE_OPS: ReadonlySet<string> = new Set([
  'findUnique',
  'findUniqueOrThrow',
]);

class TenantGuardError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'TenantGuardError';
  }
}

interface TenantGuardOptions {
  /** When true, violations on reads throw. When false (default), they log a warning. */
  strictReads?: boolean;
  /** When true, violations on writes throw. Default true. */
  strictWrites?: boolean;
  /** Supply a function that decides at request time whether to bypass the guard. */
  isBypassed?: () => boolean;
}

/**
 * Walk a `where` object looking for a `tenantId` reference anywhere in the tree
 * (direct key, inside AND/OR/NOT arrays). Returns true if found.
 */
function whereHasTenantId(where: unknown): boolean {
  if (!where || typeof where !== 'object') return false;
  const obj = where as Record<string, unknown>;
  if ('tenantId' in obj && obj['tenantId'] !== undefined) return true;

  for (const key of ['AND', 'OR']) {
    const val = obj[key];
    if (Array.isArray(val) && val.some((v) => whereHasTenantId(v))) return true;
  }
  // NOT can be an object or an array
  const not = obj['NOT'];
  if (not) {
    if (Array.isArray(not) && not.some((v) => whereHasTenantId(v))) return true;
    if (whereHasTenantId(not)) return true;
  }
  return false;
}

function dataHasTenantId(data: unknown): boolean {
  if (!data || typeof data !== 'object') return false;
  if (Array.isArray(data)) return data.every(dataHasTenantId);
  const obj = data as Record<string, unknown>;
  return 'tenantId' in obj && obj['tenantId'] !== undefined && obj['tenantId'] !== '';
}

/**
 * Prisma Client extension that enforces tenant scoping on every query touching
 * a tenant-scoped model. Writes without a tenantId throw; reads without one log
 * a warning (upgradeable to strict in Phase 2).
 *
 * To bypass for a legitimate cross-tenant operation (provisioning, cron sweep,
 * domain resolver), wrap the call in `bypassTenantGuard(() => prisma....)`.
 */
export function buildTenantGuardExtension(options: TenantGuardOptions = {}) {
  const strictReads = options.strictReads ?? false;
  const strictWrites = options.strictWrites ?? true;
  const isBypassed = options.isBypassed ?? (() => false);

  return Prisma.defineExtension({
    name: 'tenant-guard',
    query: {
      $allModels: {
        async $allOperations({ model, operation, args, query }) {
          if (!model || !TENANT_SCOPED_MODELS.has(model)) return query(args);
          if (isBypassed()) return query(args);

          const op = operation as string;

          // Write (create/createMany/upsert): require tenantId in data
          if (WRITE_CREATE_OPS.has(op)) {
            const rawArgs = args as unknown as Record<string, unknown>;
            const createPayload =
              op === 'upsert' ? rawArgs['create'] : rawArgs['data'];
            if (!dataHasTenantId(createPayload)) {
              const msg = `TenantGuard: ${op} on ${model} without tenantId in data`;
              if (strictWrites) throw new TenantGuardError(msg);
              logger.warn(msg);
            }
          }

          // Update / delete / upsert-where: require tenantId in where
          if (WRITE_UPDATE_OPS.has(op) || op === 'upsert') {
            const rawArgs = args as unknown as Record<string, unknown>;
            if (!whereHasTenantId(rawArgs['where'])) {
              const msg = `TenantGuard: ${op} on ${model} without tenantId in where`;
              if (strictWrites) throw new TenantGuardError(msg);
              logger.warn(msg);
            }
          }

          // Read (findFirst/findMany/count/aggregate/groupBy): warn if no tenantId
          if (READ_OPS.has(op)) {
            const rawArgs = args as unknown as Record<string, unknown>;
            if (!whereHasTenantId(rawArgs['where'])) {
              const msg = `TenantGuard: ${op} on ${model} without tenantId in where`;
              if (strictReads) throw new TenantGuardError(msg);
              // Keep this quiet (debug) — the signal matters in Phase 2. In Phase 1
              // we only wire the plumbing.
              logger.debug(msg);
            }
          }

          // findUnique operations — checked only if the unique key includes tenantId
          // at schema-level. No enforcement here; noted for documentation.
          if (READ_UNIQUE_OPS.has(op)) {
            // no-op
          }

          return query(args);
        },
      },
    },
  });
}

export { TenantGuardError };
