import './global.css';
import { Sidebar } from './sidebar';
import { Navbar } from './navbar';

export const metadata = {
  title: 'Welcome to desk',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen w-full flex-col bg-muted/40 lg:flex-row text-foreground bg-background">
        <Sidebar />
        <div className="flex flex-col flex-1 min-h-screen">
            <Navbar />
            <main className="flex-1 p-6 gap-4">
                {children}
            </main>
        </div>
      </body>
    </html>
  );
}
